"""Synthetic .mq5 fixtures — exercise the parser on hand-built minimal EAs."""

from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

from sq_mcp.parsers import analyze_mq5


def _write(p: Path, body: str) -> Path:
    p.write_text(textwrap.dedent(body), encoding="utf-8")
    return p


def _minimal_template(magic: int = 11111, sl_value: str = "0", pt_value: str = "0", exit_bars: int = 1) -> str:
    return f"""\
//+------------------------------------------------------------------+
//| TestStrategy 1.0 EA
//|
//|    Generated by StrategyQuant X Build 143 for MetaTrader5 (hedged)
//|    Backtested on EURUSD / H1, 2020.01.01 - 2024.01.01
//+------------------------------------------------------------------+

#property tester_indicator "SqRSI"

input int MagicNumber = {magic};
input int ExitAfterBars1 = {exit_bars};
input double mmRiskedMoney = 100.0;
input double mmMaxLots = 5.0;
input bool LimitTimeRange = true;
input string SignalTimeRangeFrom = "08:00";
input string SignalTimeRangeTo = "20:00";

bool LongEntrySignal = false;
bool ShortEntrySignal = false;
bool LongExitSignal = false;
bool ShortExitSignal = false;

void OnTick() {{
//------------------------
// Rule: Trading signals
//------------------------
//------------------------------------------------------------------
if (_sqIsBarOpen == true) {{
     LongEntrySignal = (sqIsRising(RSI_1, 2, false, 1));
     ShortEntrySignal = (sqIsFalling(RSI_1, 2, false, 1));
     LongExitSignal = false;
     ShortExitSignal = false;
}}

//------------------------
// Rule: Long entry
//------------------------
//------------------------------------------------------------------
   if (LongEntrySignal) {{
      sl = sqFixMarketPrice({sl_value}, "Current");
      pt = sqFixMarketPrice({pt_value}, "Current");
      _ticket = openPosition(ORDER_TYPE_BUY_STOP, "Current", size, openPrice, sl, pt, 5, "", MagicNumber, 0, true, false);
      sqSetExitAfterXBars(_ticket, ExitAfterBars1);
   }}

//------------------------
// Rule: Short entry
//------------------------
//------------------------------------------------------------------
   if (ShortEntrySignal) {{
      sl = sqFixMarketPrice({sl_value}, "Current");
      pt = sqFixMarketPrice({pt_value}, "Current");
      _ticket = openPosition(ORDER_TYPE_SELL_STOP, "Current", size, openPrice, sl, pt, 5, "", MagicNumber, 0, true, false);
      sqSetExitAfterXBars(_ticket, ExitAfterBars1);
   }}
}}

// Helper code further down — should NOT be picked up by SL/PT scoping
void HelperFunction() {{
   sl = HistoryOrderGetDouble(orderId, ORDER_SL);
   sl = NormalizeDouble(sl, 5);
}}
"""


def test_synthetic_ea_no_sl_no_pt(tmp_path):
    p = _write(tmp_path / "ea.mq5", _minimal_template(sl_value="0", pt_value="0"))
    s = analyze_mq5(p)
    assert s.has_stop_loss is False
    assert s.has_profit_target is False
    codes = {f.code for f in s.findings}
    assert "NO_STOP_LOSS" in codes
    assert "NO_PROFIT_TARGET" in codes
    assert "MM_FIXED_AMOUNT_NO_SL" in codes


def test_synthetic_ea_with_real_sl(tmp_path):
    p = _write(tmp_path / "ea.mq5", _minimal_template(sl_value="50", pt_value="100"))
    s = analyze_mq5(p)
    assert s.has_stop_loss is True
    assert s.has_profit_target is True
    codes = {f.code for f in s.findings}
    assert "NO_STOP_LOSS" not in codes
    assert "MM_FIXED_AMOUNT_NO_SL" not in codes


def test_synthetic_ea_default_magic_number_flagged(tmp_path):
    p = _write(tmp_path / "ea.mq5", _minimal_template(magic=11111))
    s = analyze_mq5(p)
    codes = {f.code for f in s.findings}
    assert "DEFAULT_MAGIC_NUMBER" in codes


def test_synthetic_ea_unique_magic_not_flagged(tmp_path):
    p = _write(tmp_path / "ea.mq5", _minimal_template(magic=42424242))
    s = analyze_mq5(p)
    codes = {f.code for f in s.findings}
    assert "DEFAULT_MAGIC_NUMBER" not in codes


def test_synthetic_ea_short_hold_flagged(tmp_path):
    p = _write(tmp_path / "ea.mq5", _minimal_template(exit_bars=1))
    s = analyze_mq5(p)
    codes = {f.code for f in s.findings}
    assert "VERY_SHORT_HOLD" in codes


def test_synthetic_ea_long_hold_not_flagged(tmp_path):
    p = _write(tmp_path / "ea.mq5", _minimal_template(exit_bars=24))
    s = analyze_mq5(p)
    codes = {f.code for f in s.findings}
    assert "VERY_SHORT_HOLD" not in codes


def test_helper_code_does_not_pollute_sl_detection(tmp_path):
    """Regression: the parser used to pick up `sl = HistoryOrderGetDouble(...)`
    in helper code, falsely concluding there was a real SL. Verify it's scoped."""
    p = _write(tmp_path / "ea.mq5", _minimal_template(sl_value="0"))
    s = analyze_mq5(p)
    assert s.has_stop_loss is False, "SL detection must be scoped to entry rule blocks"


def test_long_entry_expression_not_declaration(tmp_path):
    """Regression: the parser used to capture `bool LongEntrySignal = false;`
    declaration instead of the actual rule body. Verify it picks up the rule."""
    p = _write(tmp_path / "ea.mq5", _minimal_template())
    s = analyze_mq5(p)
    assert s.long_entry_expr is not None
    assert "false" != s.long_entry_expr.lower()
    assert "sqIsRising" in s.long_entry_expr


def test_empty_file_rejected(tmp_path):
    p = tmp_path / "empty.mq5"
    p.write_text("")
    with pytest.raises(ValueError, match="empty"):
        analyze_mq5(p)


def test_oversize_file_rejected(tmp_path):
    p = tmp_path / "huge.mq5"
    p.write_bytes(b"// junk\n" * (1024 * 1024))  # 8 MB
    with pytest.raises(ValueError, match="bytes"):
        analyze_mq5(p)


def test_missing_file_raises(tmp_path):
    with pytest.raises(FileNotFoundError):
        analyze_mq5(tmp_path / "nope.mq5")


def test_crypto_no_sl_is_critical(tmp_path):
    body = _minimal_template(sl_value="0").replace(
        "Backtested on EURUSD / H1", "Backtested on BTCUSDT / M5"
    )
    p = _write(tmp_path / "btc.mq5", body)
    s = analyze_mq5(p)
    no_sl = next(f for f in s.findings if f.code == "NO_STOP_LOSS")
    assert no_sl.severity == "critical"


def test_forex_no_sl_is_high_not_critical(tmp_path):
    p = _write(tmp_path / "eur.mq5", _minimal_template(sl_value="0"))
    s = analyze_mq5(p)
    no_sl = next(f for f in s.findings if f.code == "NO_STOP_LOSS")
    assert no_sl.severity == "high"
