"""Static analysis tools — MQL5 risk audit, .sqx introspection, comparison.

These do NOT need the SQ engine running — they parse files in pure Python,
which means they work offline and even before SQ X is installed. They are the
reason the plugin can give value the moment a strategy file lands on disk.
"""

from __future__ import annotations

from mcp.server.fastmcp import Context, FastMCP
from pydantic import BaseModel, Field

from sq_mcp._validation import ValidationError, resolve_safe_path
from sq_mcp.parsers import analyze_mq5, parse_cfx
from sq_mcp.tools._common import safe_error_payload


class Mq5PathArgs(BaseModel):
    path: str = Field(..., description="Absolute path to a .mq5 file generated by SQ X.")


class CompareMq5Args(BaseModel):
    paths: list[str] = Field(..., min_length=2, max_length=20, description="Two or more (max 20) .mq5 paths to compare side-by-side.")


class CfxPathArgs(BaseModel):
    path: str = Field(..., description="Absolute path to a .cfx (project config) file.")


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        description=(
            "Analyze a SQ-generated .mq5 Expert Advisor: extracts symbol/TF, indicators, "
            "entry/exit rules, MM, and runs a risk audit (no SL, default magic number, "
            "ExitAfterBars=1 on low TF, etc.). Use this BEFORE importing or running."
        )
    )
    async def analyze_mq5_file(args: Mq5PathArgs, ctx: Context) -> dict:
        try:
            path = resolve_safe_path(args.path, must_exist=True)
            result = analyze_mq5(path)
            severity_counts = {
                sev: sum(1 for f in result.findings if f.severity == sev)
                for sev in ("critical", "high", "medium", "low", "info")
            }
            if severity_counts["critical"]:
                await ctx.error(f"{severity_counts['critical']} critical risk(s) in {path.name}")
            elif severity_counts["high"]:
                await ctx.warning(f"{severity_counts['high']} high-severity risk(s) in {path.name}")
            return {"ok": True, **result.as_dict(), "summary": severity_counts}
        except (ValidationError, ValueError, FileNotFoundError, OSError) as exc:
            return safe_error_payload(exc)

    @mcp.tool(
        description=(
            "Compare two or more .mq5 strategies side-by-side: indicators, magic numbers, "
            "time ranges, MM. Flags conflicts (same magic, identical backtest window)."
        )
    )
    async def compare_mq5_files(args: CompareMq5Args, ctx: Context) -> dict:
        try:
            results = []
            for p in args.paths:
                path = resolve_safe_path(p, must_exist=True)
                results.append(analyze_mq5(path))
            magic_collisions: dict[int, list[str]] = {}
            for r in results:
                if r.magic_number is None:
                    continue
                magic_collisions.setdefault(r.magic_number, []).append(str(r.path))
            collisions = {m: paths for m, paths in magic_collisions.items() if len(paths) > 1}
            window_keys = {
                (r.backtest_symbol, r.backtest_timeframe, r.backtest_period) for r in results
            }
            same_window = len(window_keys) == 1

            return {
                "ok": True,
                "strategies": [r.as_dict() for r in results],
                "warnings": {
                    "magic_number_collisions": collisions,
                    "all_same_backtest_window": same_window,
                },
                "summary_table": [
                    {
                        "name": r.name,
                        "symbol": r.backtest_symbol,
                        "tf": r.backtest_timeframe,
                        "magic": r.magic_number,
                        "exit_after_bars": r.exit_after_bars,
                        "has_sl": r.has_stop_loss,
                        "has_pt": r.has_profit_target,
                        "indicators_count": len(r.indicators),
                        "long_rule_chars": len(r.long_entry_expr or ""),
                        "findings_critical": sum(1 for f in r.findings if f.severity == "critical"),
                        "findings_high": sum(1 for f in r.findings if f.severity == "high"),
                    }
                    for r in results
                ],
            }
        except (ValidationError, ValueError, FileNotFoundError, OSError) as exc:
            return safe_error_payload(exc)

    @mcp.tool(description="Inspect a .cfx project config file (tasks, databanks, version) without loading SQ X.")
    async def inspect_cfx(args: CfxPathArgs, ctx: Context) -> dict:
        try:
            path = resolve_safe_path(args.path, must_exist=True)
            return {"ok": True, **parse_cfx(path).as_dict()}
        except (ValidationError, ValueError, FileNotFoundError, OSError) as exc:
            return safe_error_payload(exc)
