"""MT5 EA scaffold generator — produce safe, parameterized .mq5 files.

SQ X generates MT5 EAs but their structure is rigid and they don't
always include the guardrails this codebase considers mandatory:
non-zero stop loss, sane magic number, risk-percent sizing, max-lot
cap, friendly logging. The tools here produce a minimal but production-
shaped .mq5 source that the agent can paste alongside or instead of
SQ X's output.

These are NOT replacements for SQ X's strategy logic — they're EA
*shells* that wrap an entry signal you provide. Use cases:

- Quickly turn a tradingview alert / discretionary rule into an EA with
  proper risk controls
- Generate a custom EA that drops into a deployment pack
- Sanity-check what a properly-guarded EA looks like

Tools:

- ``mt5_ea_generate_basic`` — minimal scaffold: 1 entry, fixed SL/TP in
  points, risk-percent sizing, magic, max-lot cap, deinit cleanup.
- ``mt5_ea_generate_with_trailing`` — adds a trailing stop (move stop
  to break-even after +1R, then trail by ``trail_points``).
- ``mt5_ea_inject_risk_guardrails`` — given an arbitrary EA source,
  injects RiskPctOfEquity sizing + magic + max-lot input declarations
  *if they aren't already present*. Idempotent; reports each change.

All output is a string — the caller writes the file. Pure formatting.
"""

from __future__ import annotations

import re
from typing import Any

from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel, Field, field_validator

# ---- argument schemas ------------------------------------------------------


class MT5EAGenerateArgs(BaseModel):
    ea_name: str = Field(..., min_length=1, max_length=64)
    symbol: str = Field(..., min_length=1, max_length=32)
    magic_number: int = Field(..., gt=0, lt=2_147_483_647)
    entry_condition_code: str = Field(
        "iMA(_Symbol, _Period, 20, 0, MODE_SMA, PRICE_CLOSE) > iMA(_Symbol, _Period, 50, 0, MODE_SMA, PRICE_CLOSE)",
        min_length=1,
        max_length=2000,
    )
    sl_points: int = Field(500, gt=0, le=100_000)
    tp_points: int = Field(1000, gt=0, le=100_000)
    risk_pct: float = Field(1.0, gt=0, le=10.0)
    max_lots: float = Field(5.0, gt=0, le=1000.0)
    direction: str = "long"
    trail_points: int = Field(300, gt=0, le=100_000)  # used by trailing variant

    @field_validator("ea_name")
    @classmethod
    def _v_name(cls, v: str) -> str:
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", v):
            raise ValueError("ea_name must be a valid MQL5 identifier")
        return v

    @field_validator("direction")
    @classmethod
    def _v_dir(cls, v: str) -> str:
        if v not in {"long", "short", "both"}:
            raise ValueError("direction must be one of: long, short, both")
        return v


class MT5EAInjectArgs(BaseModel):
    source: str = Field(..., min_length=10, max_length=500_000)
    risk_pct: float = Field(1.0, gt=0, le=10.0)
    max_lots: float = Field(5.0, gt=0, le=1000.0)
    magic_number: int = Field(..., gt=0, lt=2_147_483_647)


# ---- code generation -------------------------------------------------------


_HEADER = """//+------------------------------------------------------------------+
//|                                                  {name}.mq5 |
//|                       Generated by sq-mcp mt5_ea_template       |
//| Includes: risk-pct sizing, magic, SL/TP in points, max-lot cap. |
//+------------------------------------------------------------------+
#property copyright   "sq-mcp"
#property link        "https://github.com/anthropics/claude-code"
#property version     "1.00"
#property strict

#include <Trade\\Trade.mqh>

input int    MagicNumber  = {magic};
input double RiskPctEquity = {risk_pct};
input double MaxLots       = {max_lots};
input int    SLPoints      = {sl_points};
input int    TPPoints      = {tp_points};

CTrade trade;
"""


_HELPERS = """
//+------------------------------------------------------------------+
//| Calculate lot size based on RiskPctEquity and SL distance.       |
//+------------------------------------------------------------------+
double LotSizeFromRisk(double sl_distance_price)
{
   if(sl_distance_price <= 0) return(0.0);
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double risk_money = equity * (RiskPctEquity / 100.0);
   double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tick_size  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tick_size <= 0 || tick_value <= 0) return(0.0);
   double sl_money_per_lot = (sl_distance_price / tick_size) * tick_value;
   if(sl_money_per_lot <= 0) return(0.0);
   double raw_lots = risk_money / sl_money_per_lot;
   double lot_step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double min_lot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double max_lot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   if(lot_step > 0) raw_lots = MathFloor(raw_lots / lot_step) * lot_step;
   raw_lots = MathMax(min_lot, MathMin(max_lot, raw_lots));
   raw_lots = MathMin(raw_lots, MaxLots);
   return(raw_lots);
}

//+------------------------------------------------------------------+
//| Is there already an open position for this magic number?         |
//+------------------------------------------------------------------+
bool HasOpenPositionForMagic()
{
   for(int i=PositionsTotal()-1; i>=0; --i)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
      {
         if((long)PositionGetInteger(POSITION_MAGIC) == MagicNumber &&
            PositionGetString(POSITION_SYMBOL) == _Symbol) return(true);
      }
   }
   return(false);
}
"""


_INIT_DEINIT = """
//+------------------------------------------------------------------+
//| Standard lifecycle handlers.                                      |
//+------------------------------------------------------------------+
int OnInit()
{
   trade.SetExpertMagicNumber(MagicNumber);
   PrintFormat("%s initialized. Magic=%d Risk=%.2f%% MaxLots=%.2f",
               MQLInfoString(MQL5_PROGRAM_NAME), MagicNumber, RiskPctEquity, MaxLots);
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   PrintFormat("%s deinit (reason=%d)", MQLInfoString(MQL5_PROGRAM_NAME), reason);
}
"""


def _tick_body_basic(direction: str, condition: str) -> str:
    blocks: list[str] = []
    if direction in {"long", "both"}:
        blocks.append(
            f"""   // ---- long entry ----
   if(!HasOpenPositionForMagic())
   {{
      bool long_signal = ({condition});
      if(long_signal)
      {{
         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
         double sl = ask - SLPoints * point;
         double tp = ask + TPPoints * point;
         double lots = LotSizeFromRisk(ask - sl);
         if(lots > 0) trade.Buy(lots, _Symbol, ask, sl, tp, "sq-mcp:long");
      }}
   }}"""
        )
    if direction in {"short", "both"}:
        blocks.append(
            f"""   // ---- short entry ----
   if(!HasOpenPositionForMagic())
   {{
      bool short_signal = !({condition});
      if(short_signal)
      {{
         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
         double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
         double sl = bid + SLPoints * point;
         double tp = bid - TPPoints * point;
         double lots = LotSizeFromRisk(sl - bid);
         if(lots > 0) trade.Sell(lots, _Symbol, bid, sl, tp, "sq-mcp:short");
      }}
   }}"""
        )
    return "\n\n".join(blocks)


def _trail_helper() -> str:
    return """
//+------------------------------------------------------------------+
//| Move SL to break-even after +1R, then trail by TrailPoints.       |
//+------------------------------------------------------------------+
input int TrailPoints = {trail_points};

void ApplyTrailing()
{
   for(int i=PositionsTotal()-1; i>=0; --i)
   {
      ulong ticket = PositionGetTicket(i);
      if(!PositionSelectByTicket(ticket)) continue;
      if((long)PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

      double point     = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
      double open_pr   = PositionGetDouble(POSITION_PRICE_OPEN);
      double cur_sl    = PositionGetDouble(POSITION_SL);
      double cur_tp    = PositionGetDouble(POSITION_TP);
      ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);

      if(type == POSITION_TYPE_BUY)
      {
         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
         double r_unit = (open_pr - cur_sl);
         if(r_unit <= 0) continue;
         if(bid - open_pr > r_unit && cur_sl < open_pr)
            trade.PositionModify(ticket, open_pr, cur_tp);
         double trail_sl = bid - TrailPoints * point;
         if(trail_sl > cur_sl) trade.PositionModify(ticket, trail_sl, cur_tp);
      }
      else if(type == POSITION_TYPE_SELL)
      {
         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double r_unit = (cur_sl - open_pr);
         if(r_unit <= 0) continue;
         if(open_pr - ask > r_unit && cur_sl > open_pr)
            trade.PositionModify(ticket, open_pr, cur_tp);
         double trail_sl = ask + TrailPoints * point;
         if(trail_sl < cur_sl) trade.PositionModify(ticket, trail_sl, cur_tp);
      }
   }
}
"""


def _generate_basic(args: MT5EAGenerateArgs) -> str:
    header = _HEADER.format(
        name=args.ea_name,
        magic=args.magic_number,
        risk_pct=args.risk_pct,
        max_lots=args.max_lots,
        sl_points=args.sl_points,
        tp_points=args.tp_points,
    )
    body = _tick_body_basic(args.direction, args.entry_condition_code)
    on_tick = f"""
//+------------------------------------------------------------------+
//| Main tick handler.                                                |
//+------------------------------------------------------------------+
void OnTick()
{{
{body}
}}
"""
    return header + _HELPERS + _INIT_DEINIT + on_tick


def _generate_with_trailing(args: MT5EAGenerateArgs) -> str:
    header = _HEADER.format(
        name=args.ea_name,
        magic=args.magic_number,
        risk_pct=args.risk_pct,
        max_lots=args.max_lots,
        sl_points=args.sl_points,
        tp_points=args.tp_points,
    )
    trail = _trail_helper().replace("{trail_points}", str(args.trail_points))
    body = _tick_body_basic(args.direction, args.entry_condition_code)
    on_tick = f"""
//+------------------------------------------------------------------+
//| Main tick handler.                                                |
//+------------------------------------------------------------------+
void OnTick()
{{
   ApplyTrailing();
{body}
}}
"""
    return header + _HELPERS + trail + _INIT_DEINIT + on_tick


def _inject_guardrails(args: MT5EAInjectArgs) -> dict[str, Any]:
    """Insert input declarations + helper if not already present.

    This is conservative: it only adds *missing* pieces, and lists what it
    did. It never replaces existing trade logic.
    """
    src = args.source
    changes: list[str] = []

    additions: list[str] = []
    if "input int MagicNumber" not in src and "input int    MagicNumber" not in src:
        additions.append(f"input int MagicNumber = {args.magic_number};")
        changes.append("added input: MagicNumber")
    if "RiskPctEquity" not in src:
        additions.append(f"input double RiskPctEquity = {args.risk_pct};")
        changes.append("added input: RiskPctEquity")
    if "MaxLots" not in src:
        additions.append(f"input double MaxLots = {args.max_lots};")
        changes.append("added input: MaxLots")

    if not additions and "LotSizeFromRisk" in src:
        return {"ok": True, "source": src, "changes": [], "note": "no changes needed — already has guardrails"}

    # Insert additions after `#property strict` if present, else at top
    insertion = "\n// ---- sq-mcp injected risk inputs ----\n" + "\n".join(additions) + "\n"
    if "#property strict" in src:
        src = src.replace("#property strict", "#property strict" + insertion, 1)
    else:
        src = insertion + src

    if "LotSizeFromRisk" not in src:
        src += _HELPERS
        changes.append("appended LotSizeFromRisk + HasOpenPositionForMagic helpers")

    return {"ok": True, "source": src, "changes": changes}


# ---- MCP registration ------------------------------------------------------


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        description=(
            "Generate a minimal MT5 EA source (.mq5) with proper risk-percent "
            "sizing, magic-number filtering, SL/TP in points, max-lot cap, and "
            "a single entry condition you supply as MQL5 boolean expression. "
            "Use as a base for hand-rolled EAs or to wrap an alert-style "
            "signal in proper risk controls. Returns the source string."
        )
    )
    async def mt5_ea_generate_basic(args: MT5EAGenerateArgs) -> dict:
        src = _generate_basic(args)
        return {
            "ok": True,
            "ea_name": args.ea_name,
            "source": src,
            "byte_size": len(src.encode("utf-8")),
            "next_steps": [
                "save as .mq5 in MetaEditor",
                "Compile (F7)",
                "drag onto a chart and check the inputs panel",
            ],
        }

    @mcp.tool(
        description=(
            "Same as mt5_ea_generate_basic, but additionally inserts a trailing "
            "stop: moves stop to break-even after +1R, then trails by "
            "trail_points. Includes the same risk-percent sizing + magic + "
            "max-lot guardrails. Returns the source string."
        )
    )
    async def mt5_ea_generate_with_trailing(args: MT5EAGenerateArgs) -> dict:
        src = _generate_with_trailing(args)
        return {
            "ok": True,
            "ea_name": args.ea_name,
            "source": src,
            "byte_size": len(src.encode("utf-8")),
            "next_steps": [
                "save as .mq5 in MetaEditor",
                "Compile (F7)",
                "set TrailPoints input on the chart",
            ],
        }

    @mcp.tool(
        description=(
            "Given an existing .mq5 source string, idempotently inject the "
            "minimum-viable risk guardrails: RiskPctEquity / MaxLots / "
            "MagicNumber input declarations + LotSizeFromRisk helper. Only "
            "adds what's missing; lists each change. The caller writes the "
            "resulting source to a file."
        )
    )
    async def mt5_ea_inject_risk_guardrails(args: MT5EAInjectArgs) -> dict:
        return _inject_guardrails(args)
