"""MetaTrader 5 .set / .ini config file parser and writer.

MT5's strategy tester saves expert advisor input parameters to a .set
file (key=value lines with section markers like ``;Auto generated by
test #1``). Some users keep multiple .set variants per EA for different
symbols, accounts, or risk profiles. This module reads/writes them
without touching the workspace state.

Tools:

- ``mt5_set_parse`` — parse a .set or .ini file (or raw text) into a
  dict of {section: {key: value}}.
- ``mt5_set_diff`` — diff two parsed .set files; report added /
  removed / changed keys.
- ``mt5_set_merge`` — merge a second .set into a base; with override
  control.
- ``mt5_set_render`` — render a dict back into .set text.
- ``mt5_set_apply_profile`` — apply a risk profile (ultra/conservative/
  moderate/aggressive) to a parsed .set by overriding LotSize,
  MaxRiskPercent, MagicNumber.

Pure text/dict transformations. Read-only file inputs, write tools
default to dry_run.
"""

from __future__ import annotations

from typing import Any

from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel, Field

from sq_mcp._validation import ValidationError, resolve_safe_path


class ParseSetArgs(BaseModel):
    set_path: str | None = None
    raw_text: str | None = None


class DiffSetArgs(BaseModel):
    a_path: str | None = None
    a_text: str | None = None
    b_path: str | None = None
    b_text: str | None = None


class MergeSetArgs(BaseModel):
    base_path: str | None = None
    base_text: str | None = None
    overlay_path: str | None = None
    overlay_text: str | None = None
    overlay_wins: bool = True


class RenderSetArgs(BaseModel):
    sections: dict[str, dict[str, str]] = Field(..., min_length=1, max_length=100)


class ApplyProfileSetArgs(BaseModel):
    set_path: str | None = None
    set_text: str | None = None
    profile: str = Field(..., min_length=1, max_length=64)
    magic_number: int = Field(0, ge=0, le=2_147_483_647)


PROFILE_MAP: dict[str, dict[str, str]] = {
    "ultra_conservative": {
        "LotSize": "0.01",
        "MaxRiskPercent": "0.5",
        "MaxDailyLossPercent": "1.0",
    },
    "conservative": {
        "LotSize": "0.05",
        "MaxRiskPercent": "1.0",
        "MaxDailyLossPercent": "2.0",
    },
    "moderate": {
        "LotSize": "0.1",
        "MaxRiskPercent": "2.0",
        "MaxDailyLossPercent": "4.0",
    },
    "aggressive": {
        "LotSize": "0.5",
        "MaxRiskPercent": "5.0",
        "MaxDailyLossPercent": "10.0",
    },
}


def _read_text(path_arg: str | None, raw_arg: str | None) -> tuple[str | None, str | None]:
    """Return (text, error). One of (path_arg, raw_arg) must be set."""
    if raw_arg is not None:
        return raw_arg, None
    if path_arg is None:
        return None, "must supply either path or text"
    try:
        p = resolve_safe_path(path_arg, must_exist=True)
    except ValidationError as e:
        return None, str(e)
    try:
        return p.read_text(encoding="utf-8", errors="replace"), None
    except OSError as e:
        return None, str(e)


def _parse_set_text(text: str) -> dict[str, Any]:
    sections: dict[str, dict[str, str]] = {"default": {}}
    current = "default"
    n_lines = 0
    n_keys = 0
    for raw in text.splitlines():
        n_lines += 1
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip() or "default"
            sections.setdefault(current, {})
            continue
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        sections[current][k.strip()] = v.strip()
        n_keys += 1
    # Drop "default" if empty (i.e. file had only sectioned content)
    if "default" in sections and not sections["default"]:
        del sections["default"]
    return {"sections": sections, "n_lines": n_lines, "n_keys": n_keys}


def _render_set(sections: dict[str, dict[str, str]]) -> str:
    lines: list[str] = []
    keys = list(sections.keys())
    # default section first (if present)
    if "default" in keys:
        keys.remove("default")
        keys.insert(0, "default")
    for sec in keys:
        if sec != "default":
            lines.append(f"[{sec}]")
        for k, v in sections[sec].items():
            lines.append(f"{k}={v}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _diff(a: dict[str, dict[str, str]], b: dict[str, dict[str, str]]) -> dict[str, Any]:
    added: dict[str, dict[str, str]] = {}
    removed: dict[str, dict[str, str]] = {}
    changed: dict[str, dict[str, dict[str, str]]] = {}
    all_secs = set(a.keys()) | set(b.keys())
    for sec in all_secs:
        a_keys = a.get(sec, {})
        b_keys = b.get(sec, {})
        for k, v in b_keys.items():
            if k not in a_keys:
                added.setdefault(sec, {})[k] = v
            elif a_keys[k] != v:
                changed.setdefault(sec, {})[k] = {"from": a_keys[k], "to": v}
        for k, v in a_keys.items():
            if k not in b_keys:
                removed.setdefault(sec, {})[k] = v
    return {
        "added": added,
        "removed": removed,
        "changed": changed,
        "n_added": sum(len(v) for v in added.values()),
        "n_removed": sum(len(v) for v in removed.values()),
        "n_changed": sum(len(v) for v in changed.values()),
    }


def _merge(
    base: dict[str, dict[str, str]],
    overlay: dict[str, dict[str, str]],
    overlay_wins: bool,
) -> dict[str, dict[str, str]]:
    out: dict[str, dict[str, str]] = {k: dict(v) for k, v in base.items()}
    for sec, kvs in overlay.items():
        bucket = out.setdefault(sec, {})
        for k, v in kvs.items():
            if k not in bucket or overlay_wins:
                bucket[k] = v
    return out


def _apply_profile(
    sections: dict[str, dict[str, str]], profile: str, magic_number: int
) -> dict[str, Any]:
    if profile not in PROFILE_MAP:
        return {
            "ok": False,
            "error": f"unknown profile {profile!r}; valid: {sorted(PROFILE_MAP)}",
        }
    overrides = dict(PROFILE_MAP[profile])
    if magic_number > 0:
        overrides["MagicNumber"] = str(magic_number)
    target_section = next(iter(sections.keys()), "default")
    sections.setdefault(target_section, {})
    applied: dict[str, str] = {}
    for k, v in overrides.items():
        sections[target_section][k] = v
        applied[k] = v
    return {
        "ok": True,
        "profile": profile,
        "target_section": target_section,
        "applied_overrides": applied,
        "rendered": _render_set(sections),
    }


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        description=(
            "Parse a .set or .ini file (or raw text) into {section: {key: "
            "value}}. Default section is named 'default' when no [section] "
            "header is present. Read-only."
        )
    )
    async def mt5_set_parse(args: ParseSetArgs) -> dict:
        text, err = _read_text(args.set_path, args.raw_text)
        if err:
            return {"ok": False, "error": err}
        return {"ok": True, **_parse_set_text(text or "")}

    @mcp.tool(
        description=(
            "Diff two .set files (or texts). Reports added / removed / changed "
            "keys per section. Useful when comparing parameter exports across "
            "optimization runs."
        )
    )
    async def mt5_set_diff(args: DiffSetArgs) -> dict:
        a_text, a_err = _read_text(args.a_path, args.a_text)
        b_text, b_err = _read_text(args.b_path, args.b_text)
        if a_err:
            return {"ok": False, "error": f"a: {a_err}"}
        if b_err:
            return {"ok": False, "error": f"b: {b_err}"}
        a_sections = _parse_set_text(a_text or "")["sections"]
        b_sections = _parse_set_text(b_text or "")["sections"]
        return {"ok": True, **_diff(a_sections, b_sections)}

    @mcp.tool(
        description=(
            "Merge an overlay .set into a base .set. overlay_wins=true (default) "
            "means overlay's values replace base's on key collision. Returns "
            "the merged sections + rendered text."
        )
    )
    async def mt5_set_merge(args: MergeSetArgs) -> dict:
        base_text, b_err = _read_text(args.base_path, args.base_text)
        overlay_text, o_err = _read_text(args.overlay_path, args.overlay_text)
        if b_err:
            return {"ok": False, "error": f"base: {b_err}"}
        if o_err:
            return {"ok": False, "error": f"overlay: {o_err}"}
        base = _parse_set_text(base_text or "")["sections"]
        overlay = _parse_set_text(overlay_text or "")["sections"]
        merged = _merge(base, overlay, args.overlay_wins)
        return {
            "ok": True,
            "sections": merged,
            "rendered": _render_set(merged),
            "overlay_wins": args.overlay_wins,
        }

    @mcp.tool(
        description=(
            "Render a sections dict back to .set text. Inverse of mt5_set_parse. "
            "Useful for emitting a .set file the user can drop into MT5."
        )
    )
    async def mt5_set_render(args: RenderSetArgs) -> dict:
        return {"ok": True, "rendered": _render_set(args.sections)}

    @mcp.tool(
        description=(
            "Apply a risk profile (ultra_conservative / conservative / "
            "moderate / aggressive) to a parsed .set by overriding LotSize, "
            "MaxRiskPercent, MaxDailyLossPercent (and optionally MagicNumber). "
            "Returns the rendered .set text."
        )
    )
    async def mt5_set_apply_profile(args: ApplyProfileSetArgs) -> dict:
        text, err = _read_text(args.set_path, args.set_text)
        if err:
            return {"ok": False, "error": err}
        sections = _parse_set_text(text or "")["sections"]
        return _apply_profile(sections, args.profile, args.magic_number)


__all__ = [
    "ApplyProfileSetArgs",
    "DiffSetArgs",
    "MergeSetArgs",
    "ParseSetArgs",
    "PROFILE_MAP",
    "RenderSetArgs",
    "_apply_profile",
    "_diff",
    "_merge",
    "_parse_set_text",
    "_render_set",
    "register",
]
