"""Static analysis of SQ-X-generated MQL5 Expert Advisor source.

SQ-generated EAs follow a stable template, so we can reliably extract:
  - header metadata (symbol, timeframe, backtest window, SQ build)
  - input parameters (MagicNumber, ExitAfterBars, MM settings, time range)
  - entry/exit rules (sqIsRising/sqIsFalling expressions, stop/limit logic)
  - real SL/PT presence (assignments inside entry rule blocks ONLY,
    not helper code further down the file)

We then emit a list of RiskFinding objects with severity + suggestion. The
goal is to surface the foot-guns that lose people money in live trading
(no SL on crypto, magic-number collisions when running multiple EAs together,
ExitAfterBars=1 with high-spread instruments, fixed-amount MM with sl=0)
BEFORE they go live.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

log = logging.getLogger("sq_mcp.parsers.mq5")

Severity = Literal["critical", "high", "medium", "low", "info"]

# Hard cap on the file size we will load into memory. SQ EAs are ~300 KB; 5 MB
# is generous and protects against accidentally analyzing a wrong file type.
_MAX_FILE_BYTES = 5 * 1024 * 1024


@dataclass
class RiskFinding:
    severity: Severity
    code: str
    title: str
    message: str
    suggestion: str = ""
    line: int | None = None


@dataclass
class Mq5Strategy:
    path: Path
    name: str | None = None
    sq_build: str | None = None
    backtest_symbol: str | None = None
    backtest_timeframe: str | None = None
    backtest_period: str | None = None
    magic_number: int | None = None
    money_management: dict[str, str] = field(default_factory=dict)
    time_range: tuple[str, str] | None = None
    indicators: list[str] = field(default_factory=list)
    long_entry_expr: str | None = None
    short_entry_expr: str | None = None
    long_exit_expr: str | None = None
    short_exit_expr: str | None = None
    entry_order_type_long: str | None = None
    entry_order_type_short: str | None = None
    exit_after_bars: int | None = None
    has_stop_loss: bool = False
    has_profit_target: bool = False
    findings: list[RiskFinding] = field(default_factory=list)

    def as_dict(self) -> dict:
        d = {k: v for k, v in self.__dict__.items() if k != "findings"}
        d["path"] = str(self.path)
        d["findings"] = [f.__dict__ for f in self.findings]
        return d


# ---- Header / metadata regexes ----------------------------------------------

_HEADER_RE = re.compile(
    r"^//\|\s*(?P<name>\S.*?\S)\s+EA\s*$", re.MULTILINE
)
_BUILD_RE = re.compile(r"Generated by StrategyQuant X Build\s+(\S+)", re.IGNORECASE)
_BACKTEST_RE = re.compile(
    r"Backtested on\s+(?P<symbol>\S+)\s*/\s*(?P<tf>\S+)\s*,\s*(?P<period>[\d.\s\-]+)"
)
_INPUT_INT_RE = re.compile(r"^input\s+int\s+(\w+)\s*=\s*(-?\d+)\s*;", re.MULTILINE)
_INPUT_DBL_RE = re.compile(r"^input\s+double\s+(\w+)\s*=\s*(-?\d+(?:\.\d+)?)\s*;", re.MULTILINE)
_INPUT_BOOL_RE = re.compile(r"^input\s+bool\s+(\w+)\s*=\s*(true|false)\s*;", re.MULTILINE)
_INPUT_STR_RE = re.compile(r'^input\s+string\s+(\w+)\s*=\s*"([^"]*)"\s*;', re.MULTILINE)
_INDICATOR_RE = re.compile(r'^#property\s+tester_indicator\s+"([^"]+)"', re.MULTILINE)

# ---- Rule block scoping -----------------------------------------------------
#
# SQ EAs structure their trading logic in a single `// Rule: Trading signals`
# block followed by `// Rule: Long entry`, `// Rule: Short entry`,
# `// Rule: Long exit`, `// Rule: Short exit` blocks. We scope all signal /
# SL / PT extraction to these regions so we don't pick up declarations or
# helper-code assignments further down the file.

_RULE_BLOCK_RE = re.compile(
    r"//\s*Rule:\s*(?P<name>[^\n]+?)\s*\n\s*//-+\s*\n(?P<body>.*?)(?=//\s*Rule:|/\*|\Z)",
    re.DOTALL,
)

_SIGNAL_INSIDE_BLOCK_RE = {
    "long_entry": re.compile(r"\bLongEntrySignal\s*=\s*(.+?);", re.DOTALL),
    "short_entry": re.compile(r"\bShortEntrySignal\s*=\s*(.+?);", re.DOTALL),
    "long_exit": re.compile(r"\bLongExitSignal\s*=\s*(.+?);", re.DOTALL),
    "short_exit": re.compile(r"\bShortExitSignal\s*=\s*(.+?);", re.DOTALL),
}

_OPEN_LONG_RE = re.compile(
    r"openPosition\(\s*ORDER_TYPE_(\w+)", re.DOTALL
)
_SL_ASSIGN_RE = re.compile(r"\bsl\s*=\s*sqFixMarketPrice\(\s*([^,)]+)")
_PT_ASSIGN_RE = re.compile(r"\bpt\s*=\s*sqFixMarketPrice\(\s*([^,)]+)")
_SQSET_EXIT_AFTER_RE = re.compile(r"sqSetExitAfterXBars\([^,]+,\s*(\w+)\s*\)")


def analyze_mq5(path: str | Path) -> Mq5Strategy:
    """Parse and risk-audit an SQ-generated .mq5 file.

    Raises:
        FileNotFoundError: path does not exist.
        ValueError: file is too large or empty.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"{p} does not exist")
    if not p.is_file():
        raise ValueError(f"{p} is not a regular file")
    size = p.stat().st_size
    if size == 0:
        raise ValueError(f"{p} is empty")
    if size > _MAX_FILE_BYTES:
        raise ValueError(
            f"{p} is {size} bytes (limit {_MAX_FILE_BYTES}); refusing to analyze. "
            "If this is really an SQ EA, file a bug."
        )

    text = p.read_text(encoding="utf-8", errors="replace")
    inputs_int = dict(_INPUT_INT_RE.findall(text))
    inputs_dbl = dict(_INPUT_DBL_RE.findall(text))
    inputs_bool = dict(_INPUT_BOOL_RE.findall(text))
    inputs_str = dict(_INPUT_STR_RE.findall(text))

    s = Mq5Strategy(path=p)

    if m := _HEADER_RE.search(text):
        s.name = m.group("name")
    if m := _BUILD_RE.search(text):
        s.sq_build = m.group(1)
    if m := _BACKTEST_RE.search(text):
        s.backtest_symbol = m.group("symbol")
        s.backtest_timeframe = m.group("tf")
        s.backtest_period = m.group("period").strip()

    if "MagicNumber" in inputs_int:
        try:
            s.magic_number = int(inputs_int["MagicNumber"])
        except ValueError:
            log.warning("could not parse MagicNumber=%s in %s", inputs_int["MagicNumber"], p)

    s.money_management = {
        k: inputs_dbl.get(k) or inputs_int.get(k)
        for k in (
            "mmRiskedMoney",
            "mmLotsIfNoMM",
            "mmMaxLots",
            "mmMultiplier",
            "mmStep",
            "InitialCapital",
        )
        if k in inputs_dbl or k in inputs_int
    }

    if inputs_bool.get("LimitTimeRange") == "true":
        s.time_range = (
            inputs_str.get("SignalTimeRangeFrom", ""),
            inputs_str.get("SignalTimeRangeTo", ""),
        )

    s.indicators = _INDICATOR_RE.findall(text)

    # --- scoped rule-block extraction ---------------------------------------
    blocks: dict[str, str] = {}
    for m in _RULE_BLOCK_RE.finditer(text):
        blocks[m.group("name").lower().strip()] = m.group("body")

    signals_block = blocks.get("trading signals") or ""
    long_entry_block = blocks.get("long entry") or ""
    short_entry_block = blocks.get("short entry") or ""
    all_entry_blocks = long_entry_block + "\n" + short_entry_block

    if m := _SIGNAL_INSIDE_BLOCK_RE["long_entry"].search(signals_block):
        s.long_entry_expr = _normalize_expr(m.group(1))
    if m := _SIGNAL_INSIDE_BLOCK_RE["short_entry"].search(signals_block):
        s.short_entry_expr = _normalize_expr(m.group(1))
    if m := _SIGNAL_INSIDE_BLOCK_RE["long_exit"].search(signals_block):
        s.long_exit_expr = _normalize_expr(m.group(1))
    if m := _SIGNAL_INSIDE_BLOCK_RE["short_exit"].search(signals_block):
        s.short_exit_expr = _normalize_expr(m.group(1))

    if m := _OPEN_LONG_RE.search(long_entry_block):
        s.entry_order_type_long = "ORDER_TYPE_" + m.group(1)
    if m := _OPEN_LONG_RE.search(short_entry_block):
        s.entry_order_type_short = "ORDER_TYPE_" + m.group(1)

    if m := _SQSET_EXIT_AFTER_RE.search(all_entry_blocks):
        var = m.group(1)
        if var in inputs_int:
            try:
                s.exit_after_bars = int(inputs_int[var])
            except ValueError:
                pass

    # SL / PT — only consider assignments inside entry rule blocks. Helper code
    # later in the file (HistoryOrderGetDouble, NormalizeDouble) is irrelevant.
    sl_assigns = _SL_ASSIGN_RE.findall(all_entry_blocks)
    pt_assigns = _PT_ASSIGN_RE.findall(all_entry_blocks)
    s.has_stop_loss = bool(sl_assigns) and any(_is_nonzero_value(a) for a in sl_assigns)
    s.has_profit_target = bool(pt_assigns) and any(_is_nonzero_value(a) for a in pt_assigns)

    s.findings = list(_run_rules(s, text))
    return s


def _is_nonzero_value(expr: str) -> bool:
    """Return True if a captured `sqFixMarketPrice(...)` first-arg is not literal 0."""
    cleaned = expr.strip()
    if cleaned in {"0", "0.0", "0.00"}:
        return False
    try:
        return float(cleaned) != 0
    except ValueError:
        # Anything non-numeric (variable / expression) we treat as a real value
        return True


def _normalize_expr(expr: str) -> str:
    expr = re.sub(r"\s+", " ", expr).strip()
    # peel one layer of redundant outer parens
    while expr.startswith("((") and expr.endswith("))"):
        expr = expr[1:-1].strip()
    return expr


# ---- risk rules --------------------------------------------------------------

_CRYPTO_PREFIXES = ("BTC", "ETH", "XRP", "SOL", "BNB", "ADA", "DOGE", "AVAX", "MATIC")


def _run_rules(s: Mq5Strategy, _text: str) -> Iterable[RiskFinding]:
    sym = (s.backtest_symbol or "").upper()
    is_crypto = sym.startswith(_CRYPTO_PREFIXES)
    is_low_tf = (s.backtest_timeframe or "").upper() in {"M1", "M5", "M15"}

    if not s.has_stop_loss:
        yield RiskFinding(
            severity="critical" if is_crypto else "high",
            code="NO_STOP_LOSS",
            title="No StopLoss configured",
            message=(
                "All `sl =` assignments evaluate to 0. The position has no protective stop, "
                "only ExitAfterBars / signal exit. A single bad bar (gap, news, low liquidity) "
                "can blow well past the declared per-trade risk."
            ),
            suggestion=(
                "Add a StopLoss rule in SQ X (e.g. ATR-based or % of price). "
                "For crypto, never run live without a hard SL."
            ),
        )

    if not s.has_profit_target:
        yield RiskFinding(
            severity="medium",
            code="NO_PROFIT_TARGET",
            title="No ProfitTarget configured",
            message="All `pt =` assignments evaluate to 0. Trades only close via ExitAfterBars or opposite signal.",
            suggestion="Consider a take-profit or trailing-stop rule for asymmetric R:R.",
        )

    if s.exit_after_bars is not None and s.exit_after_bars <= 1:
        yield RiskFinding(
            severity="high" if is_low_tf else "medium",
            code="VERY_SHORT_HOLD",
            title=f"ExitAfterBars = {s.exit_after_bars}",
            message=(
                f"Trades exit after {s.exit_after_bars} bar(s) on {s.backtest_timeframe or 'unknown TF'}. "
                "Edge can disappear once real-broker spread + commission + slippage are applied."
            ),
            suggestion="Re-test with realistic spread+commission. Compare PnL with vs without the ExitAfterBars filter.",
        )

    if s.magic_number == 11111:
        yield RiskFinding(
            severity="high",
            code="DEFAULT_MAGIC_NUMBER",
            title="MagicNumber is the SQ default (11111)",
            message=(
                "If you load several SQ-generated EAs at once they will all share MagicNumber 11111 "
                "and can close/modify each other's orders."
            ),
            suggestion="Assign a unique MagicNumber per EA before running them in parallel.",
        )

    mm = s.money_management
    if mm:
        try:
            max_lots = float(mm.get("mmMaxLots") or 0)
        except (TypeError, ValueError):
            max_lots = 0.0
        if max_lots >= 10:
            yield RiskFinding(
                severity="medium",
                code="HIGH_MAX_LOTS",
                title=f"mmMaxLots = {mm['mmMaxLots']}",
                message="Max lot cap is high; combined with no SL this can amplify a bad trade.",
                suggestion="Lower mmMaxLots to a value matching your account size and instrument.",
            )
        if not s.has_stop_loss and "mmRiskedMoney" in mm:
            yield RiskFinding(
                severity="critical",
                code="MM_FIXED_AMOUNT_NO_SL",
                title="Fixed-amount MM is meaningless without SL",
                message=(
                    f"sqMMFixedAmount uses sl to back-calculate position size. "
                    f"With sl=0 the size formula degenerates and your real risk per trade is unbounded "
                    f"(not the {mm['mmRiskedMoney']} declared)."
                ),
                suggestion="Either add a real SL or switch to a fixed-lot / fixed-fraction MM that doesn't need SL.",
            )

    if s.backtest_period:
        yield RiskFinding(
            severity="info",
            code="VERIFY_OOS",
            title=f"Backtest window: {s.backtest_period}",
            message=(
                "An IS-only backtest cannot prove edge. Always reserve out-of-sample data, "
                "run Walk-Forward, and Monte-Carlo the trade order before going live."
            ),
            suggestion="Reserve ≥ 30% of the window as out-of-sample. Add Monte Carlo trade-order randomization in SQ X.",
        )
